/* tslint:disable */
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
export const _capnpFileId = BigInt("0xef1b5abe02e1f8d4");
export var Person_PhoneNumber_Type;
(function (Person_PhoneNumber_Type) {
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["mobile"] = 0] = "mobile";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["home"] = 1] = "home";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["work"] = 2] = "work";
})(Person_PhoneNumber_Type || (Person_PhoneNumber_Type = {}));
export class Person_PhoneNumber extends __S {
    static Type = Person_PhoneNumber_Type;
    static _capnp = { displayName: "PhoneNumber", id: "af663da31c027e0e", size: new __O(8, 1) };
    getNumber() { return __S.getText(0, this); }
    setNumber(value) { __S.setText(0, value, this); }
    getType() { return __S.getUint16(0, this); }
    setType(value) { __S.setUint16(0, value, this); }
    toString() { return "Person_PhoneNumber_" + super.toString(); }
}
export var Person_Employment_Which;
(function (Person_Employment_Which) {
    Person_Employment_Which[Person_Employment_Which["unemployed"] = 0] = "unemployed";
    Person_Employment_Which[Person_Employment_Which["employer"] = 1] = "employer";
    Person_Employment_Which[Person_Employment_Which["school"] = 2] = "school";
    Person_Employment_Which[Person_Employment_Which["selfEmployed"] = 3] = "selfEmployed";
})(Person_Employment_Which || (Person_Employment_Which = {}));
export class Person_Employment extends __S {
    static unemployed = Person_Employment_Which.unemployed;
    static employer = Person_Employment_Which.employer;
    static school = Person_Employment_Which.school;
    static selfEmployed = Person_Employment_Which.selfEmployed;
    static _capnp = { displayName: "employment", id: "e88780a90af3da0c", size: new __O(8, 4) };
    isUnemployed() { return __S.getUint16(4, this) === 0; }
    setUnemployed() { __S.setUint16(4, 0, this); }
    getEmployer() {
        __S.testWhich("employer", __S.getUint16(4, this), 1, this);
        return __S.getText(3, this);
    }
    isEmployer() { return __S.getUint16(4, this) === 1; }
    setEmployer(value) {
        __S.setUint16(4, 1, this);
        __S.setText(3, value, this);
    }
    getSchool() {
        __S.testWhich("school", __S.getUint16(4, this), 2, this);
        return __S.getText(3, this);
    }
    isSchool() { return __S.getUint16(4, this) === 2; }
    setSchool(value) {
        __S.setUint16(4, 2, this);
        __S.setText(3, value, this);
    }
    isSelfEmployed() { return __S.getUint16(4, this) === 3; }
    setSelfEmployed() { __S.setUint16(4, 3, this); }
    toString() { return "Person_Employment_" + super.toString(); }
    which() { return __S.getUint16(4, this); }
}
export class Person extends __S {
    static PhoneNumber = Person_PhoneNumber;
    static _capnp = { displayName: "Person", id: "d94307c4985be8e7", size: new __O(8, 4) };
    static _Phones;
    getId() { return __S.getUint32(0, this); }
    setId(value) { __S.setUint32(0, value, this); }
    getName() { return __S.getText(0, this); }
    setName(value) { __S.setText(0, value, this); }
    getEmail() { return __S.getText(1, this); }
    setEmail(value) { __S.setText(1, value, this); }
    adoptPhones(value) { __S.adopt(value, __S.getPointer(2, this)); }
    disownPhones() { return __S.disown(this.getPhones()); }
    getPhones() { return __S.getList(2, Person._Phones, this); }
    hasPhones() { return !__S.isNull(__S.getPointer(2, this)); }
    initPhones(length) { return __S.initList(2, Person._Phones, length, this); }
    setPhones(value) { __S.copyFrom(value, __S.getPointer(2, this)); }
    getEmployment() { return __S.getAs(Person_Employment, this); }
    initEmployment() { return __S.getAs(Person_Employment, this); }
    toString() { return "Person_" + super.toString(); }
}
export class AddressBook extends __S {
    static _capnp = { displayName: "AddressBook", id: "c06ea6d038a357bb", size: new __O(0, 1) };
    static _People;
    adoptPeople(value) { __S.adopt(value, __S.getPointer(0, this)); }
    disownPeople() { return __S.disown(this.getPeople()); }
    getPeople() { return __S.getList(0, AddressBook._People, this); }
    hasPeople() { return !__S.isNull(__S.getPointer(0, this)); }
    initPeople(length) { return __S.initList(0, AddressBook._People, length, this); }
    setPeople(value) { __S.copyFrom(value, __S.getPointer(0, this)); }
    toString() { return "AddressBook_" + super.toString(); }
}
Person._Phones = capnp.CompositeList(Person_PhoneNumber);
AddressBook._People = capnp.CompositeList(Person);
